services:
  goapp:
    build: .
    container_name: goapp
    ports:
      - "8080:8080"
    networks:
      - net

  # Serviço do Prometheus (monitoramento)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml # Especifica o arquivo de configuração do Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # Monta o arquivo de configuração do Prometheus no container (somente leitura)
    networks:
      - net

  # Serviço do Grafana (visualização de métricas)
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
    networks:
      - net

networks:
  net:
    driver: bridge # Usa o driver de rede "bridge" para comunicação entre containers
